Repository kube-logging/telemetry-controller, pull requests merged in 2025-01, with the labels that each got.

#133 feat: enable excluding log collection from pods
  README.md
  internal/controller/telemetry/otel_conf_gen/otel_col_conf_test_fixtures/complex.yaml
  internal/controller/telemetry/otel_conf_gen/otel_conf_gen.go
  internal/controller/telemetry/otel_conf_gen/otel_conf_gen_test.go
  internal/controller/telemetry/pipeline/components/processor/filter_processor.go
  internal/controller/telemetry/pipeline/components/processor/k8s_attributes_processor.go
  internal/controller/telemetry/pipeline/pipeline.go
Labels: enhancement

#134 Fix: confgen testing receivers/exporters
  internal/controller/telemetry/otel_conf_gen/otel_col_conf_test_fixtures/complex.yaml
  internal/controller/telemetry/otel_conf_gen/otel_conf_gen_test.go
  internal/controller/telemetry/pipeline/components/connector/count_connector.go
Labels: enhancement

#136 docs: add blog resources
  docs/demos/persistence-and-retry-mechanisms/README.md
  docs/demos/persistence-and-retry-mechanisms/generated-otelcol-config.yaml
  docs/demos/persistence-and-retry-mechanisms/ns.yaml
  docs/demos/persistence-and-retry-mechanisms/receivers/receiver-db.yaml
  docs/demos/persistence-and-retry-mechanisms/receivers/receiver-web.yaml
  docs/demos/persistence-and-retry-mechanisms/tc-resources/collector.yaml
  docs/demos/persistence-and-retry-mechanisms/tc-resources/tc.yaml
Labels: documentation

#138 docs: add link to blog
  docs/demos/persistence-and-retry-mechanisms/README.md
Labels: documentation

#139 fix: panic on log kv pairs
  internal/controller/telemetry/manager/tenant_resource_manager.go
Labels: bug

#135 feat: add bytes connector
  internal/controller/telemetry/collector_controller.go
  internal/controller/telemetry/otel_conf_gen/otel_col_conf_test_fixtures/complex.yaml
  internal/controller/telemetry/otel_conf_gen/otel_conf_gen.go
  internal/controller/telemetry/otel_conf_gen/otel_conf_gen_test.go
  internal/controller/telemetry/pipeline/components/connector/bytes_connector.go
  internal/controller/telemetry/pipeline/pipeline.go
Labels: enhancement

#140 chore: remove match-once since it's deprecated
  api/telemetry/v1alpha1/tenant_types.go
  charts/telemetry-controller/crds/telemetry.kube-logging.dev_tenants.yaml
  config/crd/bases/telemetry.kube-logging.dev_tenants.yaml
  internal/controller/telemetry/pipeline/components/connector/routing_connector.go
Labels: enhancement

#141 chore: update docker build
  Dockerfile
Labels: enhancement
